spring.application.name=PaymentService

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=none

spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.instances.randomServiceCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.randomServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.randomServiceCB.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.randomServiceCB.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.randomServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.randomServiceCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.randomServiceCB.permittedNumberOfCallsInHalfOpenState=3
feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000


spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=payment-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.cloud.compatibility-verifier.enabled=false